#:include force components\input_screen.kv
#:include force components\login_screen.kv

<TextInput>:
    multiline: False
    write_tab: False
    font_size: 16 
<Label>:
    font_size: 20
    color: 0.3, 0.3, 0.3, 1
<Button>:
    color: 0.8, 0.8, 0.8, 1
<PaddingBoxLayout@BoxLayout>:
    padding: 20 
<InputScreen_BoxLayout@BoxLayout>:
	size_hint_y: 0.15
	padding: 20 
<FixedSizeLabel@Label>
	size_hint_x: 0.4
<Root>:
	InputScreen:
	LoginScreen:
